### Script Generated by Control Surface Studio for Python 3 (resorted to default: no)
from .css_midi_mix_mod import css_midi_mix_mod

def create_instance(c_instance):
	return css_midi_mix_mod(c_instance)